### ISSUE TITLE
Type 469489699 not found. Invalid constructor id. 

### ISSUE THREAD

**Issue by ivorynoise** [gram-js/gramjs#205]
I got the following log. I am using telegram@2.0.6

```
[2021-12-03T18:54:56.058Z] [INFO] - [Type 469489699 not found, remaining data #���?p��g�a�g�a�?@����U�C��u?�x��5�f]
[2021-12-03T18:55:23.429Z] [INFO] - [Type 469489699 not found, remaining data #���I9��Gi�ah�a�h.i
                                                                                                 Cx9V岼ǖ�Fy@�=�/�]
.����H�]-03T18:55:36.459Z] [INFO] - [Type 469489699 not found, remaining data #���?p�(h�a'h�a�{K1%��5��qU
�&�_��ň��b��?�p,]:45.475Z] [INFO] - [Type 469489699 not found, remaining data #���I9��]i�a0h�a~�
[2021-12-03T18:56:27.428Z] [INFO] - [Type 469489699 not found, remaining data #���֩5I9��i�aZh�a����F���N���;sl�`L%R8
]
<]j5RW��τ�����:56:36.822Z] [INFO] - [Type 469489699 not found, remaining data #���֩5?p�dh�ach�a��o
[2021-12-03T18:56:44.777Z] [INFO] - [Type 469489699 not found, remaining data #���֩5I9��i�akh�ar�]�5�CW�S��}
                                                                                                           9    �{�
=]
[2021-12-03T18:56:47.720Z] [INFO] - [Type 469489699 not found, remaining data #���֩5?p�oh�anh�a�[&�s�¹�~�Q�����C�]
[2021-12-03T18:57:10.233Z] [INFO] - [Type 469489699 not found, remaining data #���?p��h�a�h�aZ�})J����QtC3�8`�s;Gvl
]
[2021-12-03T18:57:12.088Z] [INFO] - [Type 469489699 not found, remaining data #���I9���i�a�h�a�ɜ��B
gG�&�G,��B'���]
[2021-12-03T18:57:31.279Z] [INFO] - [Type 469489699 not found, remaining data #���?p��h�a�h�aY,V�BĲ�eU����(�y�WڅS]
[2021-12-03T18:57:40.457Z] [INFO] - [Type 469489699 not found, remaining data #���I9���i�a�h�a���m�����i�v5ap\�D��]
[2021-12-03T18:57:44.499Z] [INFO] - [Type 469489699 not found, remaining data #��I�%I9���i�a�h�a�.�^2�5����H%��|(��
]
```

**Comment by ivorynoise** [comment]
Related issue  #204

**Comment by rojserbest** [comment]
Are you using a dependency which requires an older version of GramJS?

**Comment by ivorynoise** [comment]
Not sure how to identify that as I am very new with JS ecosystem. I uninstalled telegram using `npm uninstall --save telegram` and reinstall it using `npm install --save telegram@2.0.6`. I got to know about version 2.0.6 using this link https://github.com/gram-js/gramjs/issues/202#issuecomment-984415160

**Comment by painor** [comment]
try to install the latest version instead of that specific one.

**Comment by ivorynoise** [comment]
I have updated the packages. My current set up is:

```
# npm outdated
Package    Current  Wanted          Latest  Location                Depended by
sequelize   6.11.0  6.11.0  6.12.0-alpha.1  node_modules/sequelize  ********
# npm list | grep telegram
├── telegram@2.0.8

```

The issue happens whenever I maintain a connect with telegram for about 1-1.5hr. This started happening since yesterday only. I ll update this issue if I it occurs again. Thanks, @painor

**Comment by happymaskterriblefate** [comment]
I've observed that this is fixed on `2.0.8`.

**Comment by ivorynoise** [comment]
@happymaskterriblefate @painor The issue still persists. Is there any way to replicate it and/or improve logging to understand what is going on behind the hoods? 

What it feels like that we have to update the deserializer. Can [TG layer  133](https://core.telegram.org/api/layers#layer-133) affect the deserialiser?

**Comment by ivorynoise** [comment]
the issue still persists after updating to v2.0.9
```
[2021-12-06T10:18:11.953Z] [INFO] - [Type 469489699 not found, remaining data #���S�eI9���ab�a��N�L����A�K���h�#g]
[2021-12-06T10:18:23.934Z] [INFO] - [Type 469489699 not found, remaining data #����jI9���an�a����\��������1��Bv�2]
[2021-12-06T10:18:26.898Z] [INFO] - [Type 469489699 not found, remaining data #����j?p�r�aq�a�(%�W*ͥG{�J��y�fm#�]
[2021-12-06T10:18:37.347Z] [INFO] - [Type 469489699 not found, remaining data #���2V??p�}�a|�a�k�r�x�p��D'g#�c���N]
[2021-12-06T10:19:14.779Z] [INFO] - [Type 469489699 not found, remaining data #���`�QI9����a��af�҅�������P?``��VT�]_�F]
[2021-12-06T10:19:26.978Z] [INFO] - [Type 469489699 not found, remaining data #���`�Q?p���a��a�
��6 �w�N��:N��Tk�ƾ]
[2021-12-06T10:19:29.706Z] [INFO] - [Type 469489699 not found, remaining data #���S�e?p���a��a܁��Ė���ُ�q��A8�<�/Z]
4�/21-12-06T10:19:46.024Z] [INFO] - [Type 469489699 not found, remaining data #���S�eI9����a��2�E
   z��3M\�q�O��G]
[2021-12-06T10:49:40.158Z] [INFO] - [Type 469489699 not found, remaining data #��I�%I9����a��ae<�1�O����9���ע�;��Q]
[2021-12-06T10:49:54.647Z] [INFO] - [Type 469489699 not found, remaining data #�����vI9����a��a��<#Y��QԬ�w�����U��厮]
[2021-12-06T10:49:59.889Z] [INFO] - [Type 469489699 not found, remaining data #����GWI9���a��ayk��ԐP�o��
lf�^��E�n]
[2021-12-06T11:18:41.282Z] [ERROR] - [Unhandled error while receiving data]
[2021-12-06T11:18:41.300Z] [ERROR] - [Error: Could not find a matching Constructor ID for the TLObject that was supposed to be
        read with ID 3169027026. Most likely, a TLObject was trying to be read when
         it should not be read. Remaining bytes: 1348]
[2021-12-06T11:18:41.301Z] [INFO] - [Type 469489699 not found, remaining data #����zI9����a��aj-v��@�r�+e�F+��>&yr��]
[2021-12-06T11:19:26.238Z] [INFO] - [Type 469489699 not found, remaining data #�����vI9����a��a���VR�y��dvra<�p&yW�]
[2021-12-06T11:19:37.103Z] [INFO] - [Type 469489699 not found, remaining data #���S�eI9����a��a6.4aU�Ƴ96$<F��:7�i]
[2021-12-06T11:20:10.463Z] [INFO] - [Type 469489699 not found, remaining data #��QF?p���a��a�4�-w�#2�����A�\��G�W�]


[2021-12-06T11:48:41.340Z] [INFO] - [Type 469489699 not found, remaining data #����GWI9�����a���aZ�%5pNr����^��B�8m9�]
[2021-12-06T11:49:13.430Z] [INFO] - [Type 469489699 not found, remaining data #����jI9�����a���a �E,���^���L�1d���E]
[2021-12-06T11:49:17.919Z] [INFO] - [Type 469489699 not found, remaining data #��

```

**Comment by painor** [comment]
does this always happen or only sometimes?

**Comment by ivorynoise** [comment]
This happens always after sometime.
