### ISSUE TITLE
New Message Event With Big Channels

### ISSUE THREAD

**Issue by pedroota** [gram-js/gramjs#575]
Hello,

I'm having a problem with a feature that's supposed to show new messages. I'm trying to get messages from 7 different groups, and each group has more than 60,000 people in it. The issue is that sometimes the feature works and shows new messages, but other times it doesn't work at all.

I've tried a few things to fix it. I've put a special function right after the connection starts, and I've also set up another thing that checks every 2 seconds if there are new messages using that function. But no matter what I do, the problem still happens.

I could really use some help to figure out how to make this feature work all the time. If anyone has any ideas, I'd really appreciate it. Thank you!

![image](https://github.com/gram-js/gramjs/assets/48136045/88acf319-131c-43dd-a79e-7aeab02dec5f)

Also, here is my code

```js
const { TelegramClient } = require("telegram");
const { StoreSession } = require("telegram/sessions");
const dotenv = require("dotenv");
const input = require("input");

// Loads .env files
dotenv.config();

class TelegramClientAdapter {
  client;
  #session;

  constructor() {
    this.#session = new StoreSession("telegram-session");
    this.client = new TelegramClient(
      this.#session,
      Number(process.env.TELEGRAM_API_ID),
      process.env.TELEGRAM_API_HASH,
      { connectionRetries: 5 }
    );

    this.#bootstrap();
  }

  async #bootstrap() {
    await this.client.start({
      phoneNumber: async () => await input.text("Please enter your number: "),
      password: async () => await input.text("Please enter your password: "),
      phoneCode: async () =>
        await input.text("Please enter the code you received: "),
      onError: (err) => console.log(err),
    });
    await this.client.connect();
    await this.client.getMe();
    await this.#keep();
  }

  async #keep() {
    setInterval(async () => {
      if (!this.client.connected) {
        console.log("Não estava conectado");
        await this.client.connect();
      }

      if (this.client.checkAuthorization()) {
        await this.client.getMe();
        console.log(
          "Estado da conexão: ",
          (await this.client.checkAuthorization())
            ? "CONECTADO"
            : "DESCONECTADO"
        );
      }
    }, 10000);
  }
}

module.exports = { TelegramClientAdapter };
```

**Comment by pedroota** [comment]
Does anyone can help here?

**Comment by painor** [comment]
What method did you use to check if there are new messages? 
Telegram will sometimes skip these events for big channels if you don't show interest in them.
You can try using getEntity or getMessages or GetChannelDifference on them from time to time to show telegram that you are interested in these channels.

**Comment by pedroota** [comment]
> What method did you use to check if there are new messages? Telegram will sometimes skip these events for big channels if you don't show interest in them. You can try using getEntity or getMessages or GetChannelDifference on them from time to time to show telegram that you are interested in these channels.

Thanks for the reply, as you can see in the photo, I used the New Message Event Handler. Also, how would you implement the logic that you described? Like, would you create a setInterval with getEntity or getMessages or GetChannelDifference on each channel to show interest on the channels?

**Comment by pedroota** [comment]
Any solutions here?

**Comment by pedroota** [comment]
@painor Hey, do you have any updates?

**Comment by painor** [comment]
> > What method did you use to check if there are new messages? Telegram will sometimes skip these events for big channels if you don't show interest in them. You can try using getEntity or getMessages or GetChannelDifference on them from time to time to show telegram that you are interested in these channels.
> 
> Thanks for the reply, as you can see in the photo, I used the New Message Event Handler. Also, how would you implement the logic that you described? Like, would you create a setInterval with getEntity or getMessages or GetChannelDifference on each channel to show interest on the channels?

Yes you are exactly right. you would create an interval and calll one of these method (or all) on the channels that you want.

**Comment by pedroota** [comment]
> > > What method did you use to check if there are new messages? Telegram will sometimes skip these events for big channels if you don't show interest in them. You can try using getEntity or getMessages or GetChannelDifference on them from time to time to show telegram that you are interested in these channels.
> > 
> > 
> > Thanks for the reply, as you can see in the photo, I used the New Message Event Handler. Also, how would you implement the logic that you described? Like, would you create a setInterval with getEntity or getMessages or GetChannelDifference on each channel to show interest on the channels?
> 
> Yes you are exactly right. you would create an interval and calll one of these method (or all) on the channels that you want.

@painor Actually I've implemented a function called keepInterestOnChannels that periodically calls ``getChannelDifference`` every 5 seconds, but it doesn't seem to be working as expected. Can you help me identify what I might have done wrong?

![image](https://github.com/gram-js/gramjs/assets/48136045/e16486bf-1826-4d45-b04a-d27b34648ffb)

**Comment by pedroota** [comment]
Hey, guys! Any updates? @painor

Can someone help me?

**Comment by devagarwal007** [comment]
This is still not working can someone please help, I am not getting messages from a few channels even though I am listening to the NewMessage event.

**Comment by pedroota** [comment]
> This is still not working can someone please help, I am not getting messages from a few channels even though I am listening to the NewMessage event.

Same as me, still not working. I event put all the listeners for channels before using NewMessage Event, but no success

**Comment by devagarwal007** [comment]
here is the channel information which i am listing

{
  "fullChat": {
    "flags": 1073741857,
    "canViewParticipants": false,
    "canSetUsername": false,
    "canSetStickers": false,
    "hiddenPrehistory": false,
    "canSetLocation": false,
    "hasScheduled": false,
    "canViewStats": false,
    "blocked": false,
    "flags2": 0,
    "canDeleteChannel": false,
    "antispam": false,
    "participantsHidden": false,
    "translationsDisabled": false,
    "id": "1319949034",
    "about": "Welcome to TECHGLARE DEALS..From Now on You will get Regular Updates on Deals on Internet and Save your valuable money while shopping.\nWebsite : https://www.techglaredeals.com\nAffiliate Disclosure : https://www.techglaredeals.com/disclosure/",
    "participantsCount": 58052,
    "adminsCount": null,
    "kickedCount": null,
    "bannedCount": null,
    "onlineCount": null,
    "readInboxMaxId": 146761,
    "readOutboxMaxId": 0,
    "unreadCount": 0,
    "chatPhoto": {
      "flags": 0,
      "hasStickers": false,
      "id": "2226824046739302313",
      "accessHash": "315704637574108408",
      "fileReference": {
        "type": "Buffer",
        "data": [
          0,
          101,
          32,
          63,
          23,
          67,
          176,
          35,
          139,
          172,
          238,
          179,
          219,
          10,
          70,
          236,
          93,
          145,
          120,
          232,
          94
        ]
      },
      "date": 1537084446,
      "sizes": [
        {
          "type": "a",
          "w": 160,
          "h": 160,
          "size": 2361,
          "className": "PhotoSize"
        },
        {
          "type": "b",
          "w": 320,
          "h": 320,
          "size": 5818,
          "className": "PhotoSize"
        },
        {
          "type": "c",
          "w": 640,
          "h": 640,
          "size": 15581,
          "className": "PhotoSize"
        }
      ],
      "videoSizes": null,
      "dcId": 5,
      "className": "Photo"
    },
    "notifySettings": {
      "flags": 7,
      "showPreviews": true,
      "silent": false,
      "muteUntil": 2147483647,
      "iosSound": null,
      "androidSound": null,
      "otherSound": null,
      "storiesMuted": null,
      "storiesHideSender": null,
      "storiesIosSound": null,
      "storiesAndroidSound": null,
      "storiesOtherSound": null,
      "className": "PeerNotifySettings"
    },
    "exportedInvite": null,
    "botInfo": [],
    "migratedFromChatId": null,
    "migratedFromMaxId": null,
    "pinnedMsgId": 145889,
    "stickerset": null,
    "availableMinId": null,
    "folderId": null,
    "linkedChatId": null,
    "location": null,
    "slowmodeSeconds": null,
    "slowmodeNextSendDate": null,
    "statsDc": null,
    "pts": 287892,
    "call": null,
    "ttlPeriod": null,
    "pendingSuggestions": null,
    "groupcallDefaultJoinAs": null,
    "themeEmoticon": null,
    "requestsPending": null,
    "recentRequesters": null,
    "defaultSendAs": null,
    "availableReactions": {
      "reactions": [
        {
          "emoticon": "😁",
          "className": "ReactionEmoji"
        },
        {
          "emoticon": "😘",
          "className": "ReactionEmoji"
        },
        {
          "emoticon": "😍",
          "className": "ReactionEmoji"
        },
        {
          "emoticon": "👏",
          "className": "ReactionEmoji"
        },
        {
          "emoticon": "⚡",
          "className": "ReactionEmoji"
        },
        {
          "emoticon": "🤩",
          "className": "ReactionEmoji"
        },
        {
          "emoticon": "👍",
          "className": "ReactionEmoji"
        },
        {
          "emoticon": "🎉",
          "className": "ReactionEmoji"
        },
        {
          "emoticon": "👌",
          "className": "ReactionEmoji"
        },
        {
          "emoticon": "❤",
          "className": "ReactionEmoji"
        },
        {
          "emoticon": "🥰",
          "className": "ReactionEmoji"
        },
        {
          "emoticon": "🆒",
          "className": "ReactionEmoji"
        },
        {
          "emoticon": "💋",
          "className": "ReactionEmoji"
        },
        {
          "emoticon": "🔥",
          "className": "ReactionEmoji"
        },
        {
          "emoticon": "🏆",
          "className": "ReactionEmoji"
        },
        {
          "emoticon": "❤‍🔥",
          "className": "ReactionEmoji"
        },
        {
          "emoticon": "💯",
          "className": "ReactionEmoji"
        }
      ],
      "className": "ChatReactionsSome"
    },
    "className": "ChannelFull"
  },
  "chats": [
    {
      "flags": 8416,
      "creator": false,
      "left": false,
      "broadcast": true,
      "verified": true,
      "megagroup": false,
      "restricted": false,
      "signatures": false,
      "min": false,
      "scam": false,
      "hasLink": false,
      "hasGeo": false,
      "slowmodeEnabled": false,
      "callActive": false,
      "callNotEmpty": false,
      "fake": false,
      "gigagroup": false,
      "noforwards": false,
      "joinToSend": false,
      "joinRequest": false,
      "forum": false,
      "flags2": 0,
      "id": "1319949034",
      "accessHash": "2525532151984207689",
      "title": "TECHGLARE DEALS",
      "username": "techglaredeals",
      "photo": {
        "flags": 2,
        "hasVideo": false,
        "photoId": "2226824046739302313",
        "strippedThumb": {
          "type": "Buffer",
          "data": [
            1,
            8,
            8,
            216,
            249,
            179,
            219,
            20,
            81,
            69,
            0,
            127
          ]
        },
        "dcId": 5,
        "className": "ChatPhoto"
      },
      "date": 1671967770,
      "restrictionReason": null,
      "adminRights": null,
      "bannedRights": null,
      "defaultBannedRights": null,
      "participantsCount": null,
      "usernames": null,
      "className": "Channel"
    }
  ],
  "users": [],
  "className": "messages.ChatFull"
}

**Comment by devagarwal007** [comment]
This is working fine using telethon library, but not in gram.js. seems something going wrong with the library. Since there is a lot of code I cannot move to python and also, this can take time. Can someone please help here? :(

**Comment by pedroota** [comment]
> This is working fine using telethon library, but not in gram.js. seems something going wrong with the library. Since there is a lot of code I cannot move to python and also, this can take time. Can someone please help here? :(

Oh, wow! Is that working on Telethon? Could you please share some code made with Telethon or even some URLs? I'm really stuck with this NewMessage Event thing

**Comment by devagarwal007** [comment]
> > This is working fine using telethon library, but not in gram.js. seems something going wrong with the library. Since there is a lot of code I cannot move to python and also, this can take time. Can someone please help here? :(
> 
> Oh, wow! Is that working on Telethon? Could you please share some code made with Telethon or even some URLs? I'm really stuck with this NewMessage Event thing

Hey, I don't think you need the python code now, just uninstall the current mom package and reinstall it, this issue will be fixed and this is fixed for me

**Comment by chungnvdev** [comment]
Try to change DC:
client.session.setDC(dcId: number, serverAddress: string, port: number);
https://docs.pyrogram.org/faq/what-are-the-ip-addresses-of-telegram-data-centers
I have a problem with DC4

**Comment by ducktype** [comment]
Same problemi, specific channels does not receive notifications, no matter the channel size or other settings... Alla the other chans receive newmessage events normally.... Using latest version

**Comment by hydra1197** [comment]
Same issue

**Comment by vic9511** [comment]
any updates here? same issue ussing latest version
